---
- name: CFSSL - Creates directory certs
  file:
    path: "{{ kubernetes.kube_etcd_ca_dir }}"
    state: directory

- name: CFSSL - Copy ca-cert config files
  copy:
    src: "{{ role_path }}/files/cert-updates/"
    dest: "{{ kubernetes.kube_etcd_ca_dir }}"
    directory_mode: true
