---
- name: Set Nginx controller URL
  set_fact:
    calico_url: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ cni.calico.version }}/manifests/calico.yaml"

- name: Debug Nginx controller URL
  debug:
    var: calico_url

- name: "Install Pod network Calico"
  shell: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ cni.calico.version }}/manifests/calico.yaml >> {{ kubernetes.logs_pods_calico }}"
  args:
    chdir: "$HOME"
    creates: "{{ kubernetes.logs_pods_calico }}"
