---
- name: Set Nginx controller URL
  set_fact:
    flannel_url: "kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/{{ cni.plannel.version }}/Documentation/kube-flannel.yml"

- name: Debug Nginx controller URL
  debug:
    var: flannel_url

- name: Install Pod network Flannel
  shell: "kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/{{ cni.plannel.version }}/Documentation/kube-flannel.yml >> {{ kubernetes.logs_pods_flannel }}"
  args:
    chdir: "$HOME"
    creates: "{{ kubernetes.logs_pods_flannel }}"
