kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: sW0WK6uTuLdC8fAEH9FjfsxR0lNnTZB18Ynzpr/6KPw=
      - identity: {}
