---
- name: Checking Host Information
  hosts: ["{{ user_input if user_input != '' else 'all' }}"]
  gather_facts: false
  roles:
    - { role: checking-hosts, tags: checking-hosts }
  vars_prompt:
    - name: user_input
      prompt: "Enter the group name in hosts (or press Enter for 'all' to ignore)"
      default: "{{ groups | join(',') }}"
      private: no

- name: Ensure tests
  hosts: [ master ] 
  roles:
    - { role: tests, tags: hello }

- name: Setup NFS
  hosts: [ nfs ]
  roles:
    - { role: nfs, tags: nfs,uninstall-nfs }

- name: Ensure Nginx
  hosts: [ lb ] 
  roles:
    - { role: loadbalancer, tags: nginx,uninstall-nginx }

- name: Ensure common
  hosts: [ master ] 
  roles:
    - { role: common, tags: common,uninstall-common }
    - { role: containerd, tags: docker }

- name: Deploy Cluster K8s
  hosts: [cluster]
  roles:
    - { role: kubernetes, tags: k8s,uninstall-cluster }

- name: Setup Component
  hosts: ["master[0]"]
  run_once: true
  roles:
    - { role: cni, tags: cni-flannel,cni-calico }
    - { role: cert-manager, tags: cert }
    - { role: metallb, tags: metallb }
    - { role: ingress-nginx, tags: ingress }
    - { role: nfs, tags: k8s-nfs, when: "'uninstall-nfs' not in ansible_run_tags" }
