---
- name: Checking Host Information
  hosts: ["{{ user_input if user_input != '' else 'all' }}"]
  gather_facts: false
  tags: [checking-hosts]
  roles: [checking-hosts]
  vars_prompt:
    - name: user_input
      prompt: "Enter the group name in hosts (or press Enter for 'all' to ignore)"
      default: "{{ groups | join(',') }}"
      private: no

- name: Ensure tests
  tags: [ hello ]
  hosts: [ master ] 
  become: true
  roles: [ tests ]

- name: Ensure Nginx
  hosts: [ lb ] 
  become: true
  roles:
    - { role: loadbalancer, tags: nginx,uninstall-nginx }

- name: Ensure common
  tags: [ common ]
  # hosts: [ cluster ] 
  hosts: [ master ] 
  become: true
  roles: [ common ]

- name: Ensure docker
  tags: ['docker']
  # hosts: [cluster]
  hosts: [master]
  become: true
  roles: [ docker ]

- name: Deploy Cluster K8s
  tags: [k8s,uninstall-cluster]
  # hosts: [cluster]
  hosts: [master]
  become: true
  roles: [kubernetes]

- name: Setup CNI Flannel
  tags: [cni-flannel]
  hosts: [master]
  become: true
  roles: [flannel]

- name: Setup CNI Calico
  tags: [cni-calico]
  hosts: [master]
  become: true
  roles: [calico]

- name: Setup Cert Manager
  tags: [cert]
  hosts: [master]
  become: true
  roles: [cert-manager]

- name: Setup Metallb
  tags: [metallb]
  hosts: [master]
  become: true
  roles: [metallb]

- name: Setup Controller Ingress Nginx
  tags: [ingress]
  hosts: [master]
  become: true
  roles: [ingress-nginx]

- name: Setup NFS
  tags: [nfs]
  hosts: [all]
  become: true
  roles: [nfs]
