---
- name: Checking Host Information
  hosts: ["{{ user_input if user_input != '' else 'all' }}"]
  gather_facts: false
  roles:
    - { role: checking-hosts, tags: checking-hosts }
  vars_prompt:
    - name: user_input
      prompt: "Enter the group name in hosts (or press Enter for 'all' to ignore)"
      default: "{{ groups | join(',') }}"
      private: no

- name: Setup NFS
  hosts: [ nfs ]
  roles:
    - { role: nfs, tags: nfs }

- name: Ensure Nginx
  hosts: [ lb ] 
  roles:
    - { role: loadbalancer, tags: nginx }

- name: Ensure cfssl
  hosts: [ master ] 
  roles:
    - { role: etcd, tags: cfssl }

- name: Ensure common
  hosts: [ master ] 
  roles:
    - { role: common, tags: common }
    - { role: containerd, tags: containerd }

- name: Deploy Cluster K8s
  tags: [k8s,init,join-master,join-worker]
  hosts: [master]
  roles:
    - { role: kubernetes }
    - { role: etcd, tags: gen-certs,copy-certs, when: "'cfssl' in ansible_run_tags" }

- name: Setup Component
  hosts: ["master[0]"]
  run_once: true
  roles:
    - { role: cni, tags: cni-flannel,cni-calico }
    - { role: cert-manager, tags: cert }
    - { role: metallb, tags: metallb }
    - { role: ingress-nginx, tags: ingress }
    - { role: nfs, tags: k8s-nfs }

- name: Uninstall
  tags:
    - uninstall
    - uninstall-kubernetes
    - uninstall-containerd
    - uninstall-nginx
    - uninstall-common
  hosts: [ all ]
  roles: [ uninstall ]
