---

- name: Ensure common
  tags: [ common ]
  hosts: [ cluster ] 
  become: true
  roles: [ common ]

- name: Ensure docker
  tags: ['docker']
  hosts: [cluster]
  become: true
  roles: [ docker ]

- name: Deploy Cluster K8s
  tags: ['k8s']
  hosts: [cluster]
  become: true
  roles: [kubernetes]

- name: Setup NFS
  hosts: [all]
  become: true
  roles:
    - role: nfs
      nfs_enable:
        server: "{{ inventory_hostname in groups['nfs_server'] }}"
        clients: "{{ inventory_hostname in groups['worker'] }}"
      nfs_server: "{{ hostvars[groups['nfs_server'][0]]['ansible_host'] }}"
