---
- name: Check if kubeadm is installed
  command: kubeadm version
  ignore_errors: True
  register: kubeadm_version
  changed_when: false

- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket=/var/run/{{ containerd.container_runtime }}/{{ containerd.container_runtime }}.sock"
  ignore_errors: True
  when: kubeadm_version|failed or kubeadm_version.stdout is not search('kubeadm version')



- name: Remove Kubernetes related packages
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
    force_apt_get: yes
  with_items:
    - kubeadm
    - kubectl
    - kubelet
    - kubernetes-cni 
    - kube*
  ignore_errors: yes
  args:
    force: yes

- name: Remove containers/ps
  shell: |
    docker rm -v -f $(docker ps -qa)
  ignore_errors: yes

- name: Remove containers/volumes
  shell: |
    docker rm -vf $(docker ps -aq)
  ignore_errors: yes

- name: Remove containers/images
  shell: |
    docker rmi -f $(docker images -aq)
  ignore_errors: yes

- name: Remove container packages
  apt:
    name: "{{ item }}"
    state: absent
    allow_change_held_packages: yes
  with_items:
    - docker-engine
    - docker
    - docker.io
    - docker-ce
    - docker-ce-cli
    - containerd
    - containerd.io
    - runc
  ignore_errors: yes

- name: Remove parts
  apt:
    autoremove: yes
  ignore_errors: yes

- name: Remove components folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.kube"
    - "/etc/cni/"
    - "/etc/kubernetes/"
    - "/var/lib/dockershim"
    - "/var/lib/etcd"
    - "/var/lib/kubelet"
    - "/var/lib/etcd2/"
    - "/var/run/kubernetes"
    - "/var/lib/docker"
    - "/etc/docker"
    - "/var/run/docker.sock"
  ignore_errors: yes

- name: Remove group container (optional)
  group:
    name: docker
    state: absent
  ignore_errors: yes

- name: Clear iptables
  command: iptables -F && iptables -X
  ignore_errors: yes

- name: Clear iptables NAT table
  command: iptables -t nat -F && iptables -t nat -X
  ignore_errors: yes

- name: Clear iptables RAW table
  command: iptables -t raw -F && iptables -t raw -X
  ignore_errors: yes

- name: Clear iptables MANGLE table
  command: iptables -t mangle -F && iptables -t mangle -X
  ignore_errors: yes
