---
- name: install haproxy
  apt:
    name: haproxy
    state: present

- name: configure haproxy.cfg file
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart haproxy
