---
nfs_fstype: "ext4" # df -T / --> to check
nfs_disk_location:
nfs_export: "/data/nfs_server"
nfs_export_subnet: "*"
nfs_export_options: "rw,sync,no_subtree_check"
nfs_client_mnt_point: "/data/nfs_client"

firewall_allow_ips:
  - 192.168.101.0/24

storageclass_name: managed-nfs-storage

nfs_client_mnt_options: 

nfs_client_mnt_state: mounted

nfs_enable:
  server: true
  clients: true

nfs_configurations:
  - nfs_enable:
      server: true
      clients: true
