---
- name: ETCD - Copy ca-cert config files
  copy:
    src: "{{ role_path }}/files/certs/"
    dest: "{{ kubernetes.kube_etcd_ca_dir }}"
    directory_mode: true

- name: ETCD - Generate CA certs 
  shell: |
    cd /etc/kubernetes/pki/etcd
    /usr/local/bin/cfssl gencert -initca ca-csr.json | /usr/local/bin/cfssljson -bare ca -

- name: ETCD - Generate etcd client certs
  shell: |
    cd /etc/kubernetes/pki/etcd
    /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=client client.json | /usr/local/bin/cfssljson -bare client

- name: ETCD - Get etcd certs local machine from master0
  fetch:
    src: "{{ kubernetes.kube_etcd_ca_dir }}/{{item}}"
    dest: "{{ role_path }}/files/cert-updates/{{item}}"
    flat: yes
  with_items:
    - ca-config.json
    - ca.pem
    - ca-key.pem
    - client.pem
    - client-key.pem
