---
- include_tasks: k8s.yml

- include_tasks:
    file: init.yml
    apply:
      tags: init
  tags: init
  when: 
    - inventory_hostname in groups['master'][0]
    - "'init' in ansible_run_tags"

- include_tasks:
    file: master.yml
    apply:
      tags: join-master
  tags: join-master
  when: 
    - inventory_hostname in groups['master']
    - "'join-master' in ansible_run_tags"

- include_tasks: 
    file: worker.yml
    apply:
      tags: join-worker
  tags: join-worker
  when: 
    - inventory_hostname in groups['master']
    - "'join-worker' in ansible_run_tags"
