---
- name: Include main tasks
  import_tasks: k8s.yml

- name: Init Master
  import_tasks: master.yml
  when: inventory_hostname in groups['master'][0]

- name: Join Master
  import_tasks: master-add.yml

- name: Join Worker
  import_tasks: worker.yml
