---
- name: Include main tasks
  import_tasks: k8s.yml

- name: Init Master
  import_tasks: master.yml
  when: inventory_hostname in groups['master'][0]

- name: Join Master
  import_tasks: master-add.yml

- name: Join Worker
  import_tasks: worker.yml

- name: Uninstall Cluster
  tags: [uninstall-cluster]
  import_tasks: uninstall.yml
  when: "'uninstall-cluster' in ansible_run_tags"
