---
- name: Create an empty file for Kubeadm configuring
  copy:
    content: ""
    dest: "{{ kubernetes.file_config }}"
    force: no

- name: Configuring the container runtime including its cgroup driver
  blockinfile:
    path: "{{ kubernetes.file_config }}"
    block: |
         kind: ClusterConfiguration
         apiVersion: kubeadm.k8s.io/v1beta3
         networking:
           podSubnet: "{{ kubernetes.CIDR }}"
         ---
         kind: KubeletConfiguration
         apiVersion: kubelet.config.k8s.io/v1beta1
         runtimeRequestTimeout: "15m"
         cgroupDriver: "systemd"
         systemReserved:
           cpu: 100m
           memory: 350M
         kubeReserved:
           cpu: 100m
           memory: 50M
         enforceNodeAllocatable:
         - pods

- name: Initialize the cluster (this could take some time)
  shell: "kubeadm init --config {{ kubernetes.file_config }} >> {{ kubernetes.logs_cluster }}"
  args:
    chdir: /root/
    creates: "{{ kubernetes.logs_cluster }}"

- name: Create .kube directory
  become: yes
  become_user: root
  file:
    path: "{{ kubernetes.config }}"
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: "{{ kubernetes.file_admin_config }}"
    dest: "{{ kubernetes.config }}/config"
    remote_src: yes
    owner: root
