---
- name: Common - Gather the package facts
  package_facts:
    manager: "auto"

- name: Common - Update package lists
  apt:
    update_cache: true
    force_apt_get: true

- name: Common - Install APT Transport HTTPS
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common
    - apt-utils
    - lsb-release
  when: "'{{ item }}' not in ansible_facts.packages"

# sys container
- name: Common - Disable system SWAP
  shell: "swapoff -a"

- name: Common - Disable SWAP in fstab (Kubeadm requirement)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Common - create an empty file for the Containerd module
  copy:
    content: ""
    dest: "{{ containerd.container_module_conf }}"
    force: no

- name: Common - configure modules for Containerd
  blockinfile:
    path: "{{ containerd.container_module_conf }}"
    block: |
         overlay
         br_netfilter
# end

# sys kubernetes
- name: Common - create an empty file for Kubernetes sysctl params
  copy:
    content: ""
    dest: "{{ kubernetes.kube_sysctl_conf }}"
    force: no

- name: Common - configure sysctl params for Kubernetes
  lineinfile:
    path: "{{ kubernetes.kube_sysctl_conf }}"
    line: "{{ item }}"
  with_items:
    - 'net.bridge.bridge-nf-call-iptables  = 1'
    - 'net.ipv4.ip_forward                 = 1'
    - 'net.bridge.bridge-nf-call-ip6tables = 1'
# end

- name: Common - Apply sysctl params without reboot
  command: sysctl --system

#################### Containerd ################
- name: Common - Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# fix DEPRECATION section in apt-key
- name: Common - Copy trusted.gpg
  copy:
    src: /etc/apt/trusted.gpg
    dest: /etc/apt/trusted.gpg.d

- name: Common - add Docker's APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible.ansible_distribution|lower }} {{ ansible.ansible_distribution_release }} stable"
    filename: "{{ containerd.name }}"
    state: present
    update_cache: yes

#################### Kubernetes ################
- name: Common - Prepare apt keyring directory.
  file:
    path: "{{ kubernetes.kubernetes_keyring_file | dirname }}"
    state: directory
    mode: 0755

- name: Common - Get Kubernetes apt key.
  get_url:
    url: "https://pkgs.k8s.io/core:/{{ kubernetes.kubernetes_release_channel }}:/v{{ kubernetes.kubernetes_version }}/deb/Release.key"
    dest: "{{ kubernetes.kubernetes_keyring_file }}"
    mode: '0644'
    force: true

- name: Common - Be sure deprecated Kubernetes repository is absent.
  file:
    path: "{{ kubernetes.kube_repo_file }}"
    state: absent

- name: Common - Add Kubernetes repository.
  apt_repository:
    repo: "deb [signed-by={{ kubernetes.kubernetes_keyring_file }}] https://pkgs.k8s.io/core:/{{ kubernetes.kubernetes_release_channel }}:/v{{ kubernetes.kubernetes_version }}/deb/ /"
    filename: "{{ kubernetes.name }}"
    state: present
    update_cache: true
