---
- name: install Containerd
  apt:
    pkg: 
      - containerd.io
      # - docker-ce
      # - docker-ce-cli
      # - docker-buildx-plugin
      # - docker-compose-plugin
    state: present
    force_apt_get: true

- name: create Containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: add Containerd configuration
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml

- name: configuring the systemd cgroup driver for Containerd
  shell: sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: Enable the Containerd service and start it
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes

# - name: Enable the Docker service and start it
#   systemd:
#     name: docker
#     state: restarted
#     enabled: yes
#     daemon-reload: yes
